In [69]:
import data_utils.data_loader as ld
import importlib

In [70]:
importlib.reload(ld)
loader = ld.HSPC_data_loader('primary_config.json')

Loading and transforming to long format:   0%|          | 0/13 [00:00<?, ?it/s]

Finding data files from: /Users/akre96/Data/Human_HSPC_Project/Primary recipients /STEP 7
	Found 13 files

Loading and transforming to long format: 100%|██████████| 13/13 [00:04<00:00,  2.95it/s]

In [71]:
loader.data

,mouse_id,code,user,day,cell_type,abundance,parent_cell_type,condition,generation,exists
0,M11,GCAACTCCTGCTCGTGCCTTAGGGTCGCAGGGTAGATCGGAAGAGC...,Mary,84,b,0.196981,hsc,Unconditioned,1,1
1,M11,GCAACTTAAGACGGGTGTGCTGCGAGAGTCTCAAGATCGGAAGAGC...,Mary,84,b,1.311968,hsc,Unconditioned,1,1
2,M11,GCAACTCGCTAGGCCCTTTTTGATTCGGGTACCAGATCGGAAGAGC...,Mary,84,b,0.000000,hsc,Unconditioned,1,1
3,M11,GCAACTGTTGGGATCTTCAATCTCGTGCAGTACAGATCGGAAGAGC...,Mary,84,b,0.043113,hsc,Unconditioned,1,1
4,M11,GCAACTATGTGTCGTAGTTAGTGACGGGCTGGTAGATCGGAAGAGC...,Mary,84,b,1.854594,hsc,Unconditioned,1,1
...,...,...,...,...,...,...,...,...,...,...
853,M1,GTCGAGGAGGTCTGTCTCGTGGCGTTTGTCCATAGATCGGAAGAGC...,Mary,144,mo,0.546046,hsc,Irradiation,1,1
854,M1,TGTTACGGGGTTTCGGTACATTTGATGGAGAGGAGATCGGAAGAGC...,Mary,144,mo,0.033813,mpp,Irradiation,1,1
855,M1,GTCGAGGATGTTACGGGTTGCCCTACCCGGATGAGATCGGAAGAGC...,Mary,144,mo,0.017221,hsc,Irradiation,1,1
856,M1,TGTTACTCGGGTCAGAGTGTCGAAGTGGGCTATAGATCGGAAGAGC...,Mary,144,mo,0.033183,mpp,Irradiation,1,1
857,M1,GTCGAGCGTGCATCGCGACTGGCAGGTTAGGATAGATCGGAAGAGC...,Mary,144,mo,0.017641,hsc,Irradiation,1,1

In [47]:
import json
import pandas as pd
config = json.load(open('primary_config.json', 'r'))
lib_codes = pd.read_csv(
    config['lib_codes'],
    sep='\t',
    header=None,
    names=['lib_id', 'lib_code', 'lib_code_reverse']
)
lib_ids = pd.read_excel(
    config['lib_ids'],
    names=['mouse_id', 'condition', 'hsc_lib_id', 'mpp_lib_id']
)
lib_ids

   mouse_id      condition  hsc_lib_id  mpp_lib_id
0        M4  Unconditioned          20          17
1        M8  Unconditioned          11          15
2        M9  Unconditioned          12          16
3       M10  Unconditioned           8          14
4       M11  Unconditioned          21          18
5        M1    Irradiation          20          17
6        M2    Irradiation          21          18
7        M3    Irradiation          22          19
8        M5    Irradiation           8          14
9        M6    Irradiation          11          15
10       M7    Irradiation          12          16
11      M12       Busulfan          20          17
12      M13       Busulfan          21          18
13      M14       Busulfan           8          14
14      M15       Busulfan          11          15
15      M16       Busulfan          12          16